services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: kickabout
      POSTGRES_USER: kickabout
      POSTGRES_PASSWORD: localpass
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build: .
    image: kickabout:1.0
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/kickabout
      SPRING_DATASOURCE_USERNAME: kickabout
      SPRING_DATASOURCE_PASSWORD: localpass
    ports:
      - "8080:8080"

  prometheus:
    image: prom/prometheus:v3.13.4
    volumes:
      - ./monitoring/prometheus.yaml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    depends_on:
      - app

  grafana:
    image: grafana/grafana:13.2
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  db-data:
  prometheus-data:
  grafana-data: